package com.quantum.constants;

public class CommonConstants {
    private CommonConstants(){

    }
    public static final String SCREENSHOT="Screenshot";
    public static final String LANGUAGE="Language";
    public static final String ENGLISH="English";
    public static final String FRENCH="French";
    public static final String VALUE="value";
    public static final String TABLE_ELEMENT="arguments[0].click();";
    public static final String UNABLE_TO_LOAD_BASE_URL = "Unable to load the Base URL: ";
    public static final String VISIBILITY_TEXT = "visibility";
    public static final String THE_ELEMENT_WITH_TEXT = "The element with";
    public static final String NOT_FOUND_TEXT = " not found ";
    public static final String SUCCESSFULLY_TEXT = " successfully";
    public static final String IS_SELECTED_TEXT = " is selected";
    public static final String UNABLE_SELECT_DROPDOWN_TEXT = "Unable to select the dropdown; The element with";
    public static final String UNABLE_TO_SCROLL_TEXT = "Unable to scroll:-";
    public static final String UNABLE_TO_SWITCH_TEXT = "Unable to switch into frame";
    public static final String UNABLE_TO_ACCESS_ALERT_TEXT = "Unable to access the alert:-";
    public static final String ALERT_NOT_PRESENT_TEXT = "Alert not present";
    public static final String ALERT_PRESENT_TEXT = "Alert is present";
    public static final String CALENDER_BODY_CONTAINER_TEXT = "calendarBodyContainer";
    public static final String SCENARIO_ID_TEXT = "ScenarioID";
    public static final String IPOPUP_VERIFICATION_TEXT = "IPopupVerification";
    public static final String POSTALCODE_TEXT = "Postalcode";
    public static final String SHEET_NAME_TEXT = "9F_DNEML.xlsx";
    public static final String DECISION_MESSAGE_TEXT = "DecisionMessage";
    public static final String EMAIL_ID_TEXT = "EmailAddress";
    public static final String INPUT_FILE_XPATH = ".//input[@id='file']";
    public static final String SEARCH_LIST_EMAIL_TEXT = "\\SearchListemails.txt";
    public static final String DATE_PATTERN_YYYY_MM_DD = "yyyy/MM/dd";
    public static final String EXECUTION_DATE_TEXT = "ExecutionDate";
    public static final String EXECUTION_STATUS_TEXT = "ExecutionStatus";
    public static final String DOWNLOAD_TEXT = "\\Downloads\\";
    public static final String CUSTOMER_TAG_TEXT = "<custname>";
    public static final String CUSTOMER_NAME1_TEXT = "CustomerName1";
    public static final String DECISION_MESSAGE_CORRECT_TEXT = "Decision message displayed correctly for Email WithConsent addedtoDNEML";
    public static final String DECISION_MESSAGE_INCORRECT_TEXT = "Decision message displayed incorrectly for Email WithConsent addedtoDNEML";
    public static final String LANGUAGE_TEXT = "Language";
    public static final String ENGLISH_TEXT = "English";
    public static final String SLASH_DELIMITER_TEXT = "\\";
    public static final String ALERT_IS_DISPLAYED_TEXT = "Alert is  displayed";
    public static final String ALERT_IS_NOT_DISPLAYED_TEXT = "Alert is not displayed";
    public static final String UPDATE_BIRTHDATE_TEXT = "UpdateBirthDate";
    public static final String GENDER_TEXT = "Gender";
    public static final String USER_DIR_TEXT = "user.dir";
    public static final String RESOURCES_TEXT = "resources";
    public static final String OFFICERID_TEXT = "OfficerID";
    public static final String TRANSIT_TEXT = "Transit";
    public static final String TEXT_XML_TEXT = "text/xml";
    public static final String ENVIRONMENT_TEXT = "environment";
    public static final String AUTHORIZATION_TEXT = "Authorization";
    public static final String CONTENT_TYPE_TEXT = "Content-Type";
    public static final String CLIENT_IDENTITY_OBJECT_TEXT = "ClientIdentityObject";
    public static final String RESPONSE_CODE_TEXT = "Response Code = ";
    public static final String RESPONSE_MESSAGE_TEXT = "Response Message = ";
    public static final String IS_OK_TEXT = "b:IsOK";
    public static final String RESPONSE_IS_OK_TEXT = "Response IsOK = ";
    public static final String RESPONSE_CID = "Response CID = ";
    public static final String NA_TEXT = "NA,NA,NA";
    public static final String UPDATE_FR_TEXT = "UpdateFr";
    public static final String INTRALINK_DETAILS_SHEET_TEXT = "Intralink_details.xlsx";
    public static final String PARTY_SETUP_FOR_PERSONAL_CUST_TEXT = "PartySetupForPersonalCust";
    public static final String PARTY_INQUIRY_TEXT = "PartyInquiry";
    public static final String IS_LOADED = " is loaded";
    public static final String SERVER_IMU12="IMU 1/2";
    public static final String SERVER_IMU78="IMU 7/8";
    public static final String SERVER_IMI12="IMI 1/2";
    public static final String SERVER_IMI34="IMI 3/4";
    public static final String URL_NOT_GIVEN_TEXT="url not specified in the Configuration.properties file.";
    public static final String CIS_CID="CIS_CID";
    public static final String NON_PERSONAL_SETUP="NonPersonalSetUp";
    public static final String UPDATE_EMAIL_NOCONSENT="UpdateEmailNoConsent";
    public static final String NONPERSONAL_UPDATE="NonpersonalUpdate";
    public static final String UPDATE_PERSONAL_CUSTOMER="UpdatePersonalCustomer";
    public static final String ACCESS_BY_ACCOUNT="AccessByAccount";
    public static final String PERSONAL_UPDATE="PersonalUpdate";
    public static final String UPDATE_CONFIRM_FR="UpdateConfirmFR";
    public static final String UPDATE_PERSONAL_CUSTOMER_FR="UpdatePersonalCustomerFR";
    public static final String LOCATE_CUSTOMER="LocateCustomer";
    public static final String PERSONAL_CUSTOMER_SETUPDUALMETHOD="PersonalCustomerSetupDualMethod";
    public static final String PERSONAL_LESSTHAN12_DUALID_FRENCH="PersonalLessThan12DualIDFrench";
    public static final String CUSTOMER_AGE_LESSTHAN12="CustomerAgelessthan12";
    public static final String ABBS_CUSTOMER_FR="ABBSCustomerFR";
    public static final String PERSONAL_CUST_DUALID_12TO15_FRENCH="PersonalCustDualID12To15French";
    public static final String NONPERSONALSETUP_WITH_DDA="NonPersonalSetupWithDDA";
    public static final String PERSONALCUSTOMER_WITH_CONSENT_YES="PersonalCustomerWithConsentYes";
    public static final String LOGIN_DETAILS="LoginDetails";
    public static final String NEW_CID="NewCID";
    public static final String NEW_ACCOUNT_NUMBER="NewAccountNumber";
    public static final String UPDATED_RESULT="UpdatedResult";
    public static final String CDIC_TESTDATA_TEXT="CDIC_InterimTestData.xlsx";
    public static final String PASS_TEXT="**********Pass Statement*********  Customer products and services screen is displayed";
    public static final String ACCOUNT_TEXT="AccountNumber";
    public static final String VALUE_TEXT="value";
    public static final String PRODUCTRELATIONSHIP_TEXT="ProductRelationShip";
    public static final String PAGE_TEXT=" page";
    public static final String CUSTOMERPRODUCT_TEXT="Customer Product ";
    public static final String ONE_E_TEXT="LETTER1E";
    public static final String TWO_E_TEXT="LETTER2E";
    public static final String THREE_E_TEXT="LETTER3E";
    public static final String TWO_E_PNTA_TEXT="LETTER2EPNTA";
    public static final String THREE_E_PNTA_TEXT="LETTER3EPNTA";
    public static final String ONE_F_TEXT="LETTER1F";
    public static final String TWO_F_TEXT="LETTER2F";
    public static final String THREE_F_TEXT="LETTER3F";
    public static final String TWO_F_PNTA_TEXT="LETTER2FPNTA";
    public static final String THREE_F_PNTA_TEXT="LETTER3FPNTA";
    public static final String DEALER_TEXT="Delar_Intralink";
    public static final String SEARCHBRANCH_TEXT="SelectBranch";
    public static final String ACCOUNTTITLETWO_TEXT="Account_TitleTwo";
    public static final String CURRENTLY_IT_IS_IN_TEXT="Currently it is in ";



}
